sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- make all
deploy:
  provider: releases
  api_key:
    secure: nzlWOnLHKU7DnwRchJ1y+BwoWQgnIY8Rf/ZMoFDW8idiXJBk7uWlyAJ1vT1c6+nqd5AY8oj0uq2gaU+O2n3AUJC+BH9DEf6X8A5QdsL0GHwRK8ZOYf76jg0KUMutckJbl7phJ9mlmMl7Nj5XnWH/uEZ35BbVE4/4+Bfe6L+fPIEmDuBq0URj4LLRK0yBwM5enRs8XcTb5Zqrn1aWfRpakGmvHjpsR96hE0qwdyuPsftJ7Ke2DmRH2LJplTOXKo86vwCoRgqpiCZrrXsjTbsCLzt92gsLfSMtrQRZfdHKKthWqZDbfRNXBsM3WuyqpxTAMuSGj+xk5tVLuxN9LPYK1pJ6rWdkhXbjtwWPyw7Wer6lxHweaGM3pU3jxpf3/UcjZJHWmW5eOuLjDlp/ee235hk0aBmwTw+KOjceslSVre1r0UrYzoWcFvsOYCCzzMHrDJRVab+fcL87W5Qf0w61dCQskXjtifClkorF9Zkuq7h0uJwXGiimN29chAVqsQyzjvgI9oYkXpOfLABNhsyRqXtv3tLKXHPPrB4NHa7UyL/2V+8GVa0dXHKsWMlzlRmlces6lLa5cNpAn6wT6yPw00pz6VxZMgpcq/xMXVXLXkryRFTysXT1NzqJblgnwceGybtJIBOwSOlWDeI2UTpgXz3zi3L7DZowELmNFbdSfZM=
  file:
  - _build/bylaws.pdf
  - _build/constitution.pdf
  on:
    repo: acmumn/constitution
  skip_cleanup: true
